vegaprotocol/pennant

- src/components/candlestick-chart.tsx
- src/components/plot-area.tsx
- src/elements/element-annotation.ts
- src/elements/index.ts
Add a last price annotation as in the existing implementation.
Closes #21
> feat: add last price annotation

- src/clipboard.d.ts
- src/components/chart.tsx
- src/components/plot-area/plot-area.tsx
- src/components/plot-container/plot-container.tsx
- src/helpers/helpers-snapshot.ts
- src/helpers/index.ts
- src/stories/app.stories.tsx
- src/stories/components/chart-controls/chart-controls.stories.tsx
- src/stories/components/chart-controls/chart-controls.tsx
- src/stories/components/toaster.ts
- src/types/chart-types.ts
An initial version of chart snapshot functionality
> feat: copy chart image to clipboard

- src/components/chart-info/chart-info.tsx
- src/core/core.ts
- src/core/helpers/helpers-core-event.ts
- src/core/plot-area.ts
Prevent the user from panning/zooming so far to the left or right that there are no data points visible
> feat: constrain horizontal extent

- src/components/chart/chart.tsx
- src/components/plot-container/helpers/helpers-study-info.ts
- src/components/plot-container/plot-container.tsx
> feat: show overlay values

- README.md
- src/components/plot-container/helpers/helpers-study-info.ts
- src/helpers/helpers-spec.ts
- src/scenegraph/parse.ts
- src/stories/components/chart-controls/chart-controls.tsx
- src/types/chart-types.ts
> feat: new indicators

- src/elements/element-x-axis.ts
- src/helpers/helpers-format.test.ts
- src/helpers/helpers-format.ts
- src/index.ts
> feat: better time axis tick labels

- src/components/chart/chart.tsx
- src/components/pane-view/helpers/helpers-study-info.ts
- src/components/pane-view/pane-view.tsx
- src/components/plot-container/plot-container.tsx
- src/components/x-axis-view/x-axis-view.tsx
- src/constants.ts
- src/core/core.ts
- src/core/helpers/helpers-core-event.ts
- src/core/plot-area.ts
- src/helpers/helpers-spec.test.ts
- src/helpers/helpers-spec.ts
- src/helpers/helpers-technical-indicators.test.ts
- src/helpers/helpers-technical-indicators.ts
- src/stories/api/vega-graphql/index.ts
- src/stories/api/vega-graphql/lib/markets.ts
- src/stories/api/vega-graphql/queries/markets.ts
- src/stories/components/market-grid/index.ts
- src/stories/components/market-grid/market-grid.css
- src/stories/components/market-grid/market-grid.tsx
- src/stories/marketGrid.stories.tsx
This PR supports the market data grid view in console but is generally useful by making the charts more configurable.
> feat: simplified chart view

- .github/workflows/add_issue_new_projects.yml
Added as part of https://github.com/vegaprotocol/token-frontend/issues/1057
> Add Github action to add new issues to frontend project board

- package.json
> build: use mjs extension for modern es build entry point

- src/components/depth-chart/chart.ts
- src/components/depth-chart/depth-chart.stories.tsx
- src/components/depth-chart/depth-chart.tsx
- src/components/depth-chart/ui.ts
- src/components/non-ideal-state/non-ideal-state.css
> feat: handle empty depth chart data

- package.json
- rollup.config.js
> build: remove es module entry points

- src/components/chart/chart.tsx
- src/components/plot-container/plot-container.tsx
- src/helpers/helpers-spec.test.ts
- src/helpers/helpers-spec.ts
- src/stories/app.stories.tsx
- src/stories/components/chart-controls/chart-controls.stories.tsx
- src/stories/components/chart-controls/chart-controls.tsx
> feat: support multiple studies

- src/helpers/helpers-spec.test.ts
- src/helpers/helpers-spec.ts
> fix: red candles should be filled

- src/styles/variables.css
> fix: use true black for background

- src/helpers/helpers-spec.test.ts
- src/helpers/helpers-spec.ts
> fix: use theme for area chart background

- src/components/chart/chart.tsx
- src/core/core.ts
- src/helpers/helpers-interval.test.ts
- src/helpers/helpers-interval.ts
- src/stories/app.stories.tsx
- src/stories/components/chart-controls/chart-controls.stories.tsx
- src/stories/components/chart-controls/chart-controls.tsx
- src/types/interval.ts
> feat: export interval labels

- src/components/chart/helpers/helpers-color.ts
- src/components/pane-view/helpers/helpers-study-info.ts
- src/helpers/helpers-spec.test.ts
- src/helpers/helpers-spec.ts
- src/scenegraph/parse.ts
- src/stories/app.stories.tsx
- src/styles/variables.css
> feat: use more appropriate colours for light theme

- package.json
- yarn.lock
> chore(deps): remove @types/classnames dependency

- src/styles/variables.css
Using darker colours for light theme to increase contrast and legibility.
> Updating success/danger colours for light/dark theme (#558)

- src/components/chart/helpers/helpers-color.ts
- src/helpers/helpers-spec.test.ts
- src/helpers/helpers-spec.ts
- src/styles/variables.css
> feat: customize color of volume bar depending on price increase/decrease

- package.json
- src/stories/app.stories.css
- src/stories/app.stories.tsx
- src/stories/components/chart-controls/chart-controls.tsx
- src/stories/components/market-grid/market-grid.tsx
- src/stories/data-source/__generated__/Candles.ts
- src/stories/data-source/__generated__/Chart.ts
- src/stories/data-source/__generated__/markets.ts
- src/stories/data-source/__generated__/types.ts
- src/stories/data-source/create-annotations.ts
- src/stories/data-source/number.tsx
- src/stories/data-source/vega-protocol-data-source.ts
- src/stories/marketGrid.stories.tsx
- yarn.lock
Candlestick demo and market grid now up and running.
> chore: fix vega protocol stories

- src/util/misc/data.test.ts
- src/util/misc/data.ts
Piggy-back on the `mergeData` function to ensure data is sorted in increasing `date` order.
> feat: sort candlestick chart data

- .github/workflows/pages.yml
Switch from Netlify hosting to Github Pages
> Add pages deployment workflow

- src/feature/candlestick-chart/candlestick-chart.tsx
- src/stories/data-source/crypto-compare-data-source.ts
- src/stories/data-source/empty-data-source.ts
- src/stories/data-source/json-data-source.ts
- src/ui/components/pane-view/pane-view.tsx
- src/ui/components/plot-container/plot-container.tsx
- src/ui/core/core.ts
- src/util/types/data-source.ts
> feat(candlestick): support position decimal places

- src/feature/candlestick-chart/candlestick-chart.stories.tsx
- src/feature/candlestick-chart/candlestick-chart.tsx
- src/stories/data-source/json-data-source.ts
- src/stories/data-source/vega-protocol-data-source.ts
- src/ui/components/pane-view/helpers/helpers-study-info.ts
- src/ui/components/pane-view/pane-view.tsx
- src/ui/components/plot-container/plot-container.tsx
- src/util/misc/specification.ts
- src/util/types/data-source.ts
- src/util/vega-lite/channeldef.ts
> feat: support multiple price monitoring bounds

- .storybook/preview.js
- src/ui/elements/html/element-label-annotation.css
- src/ui/elements/html/element-label-annotation.ts
- src/ui/elements/html/element-label.stories.tsx
- src/util/types/annotation.ts
> feat: support formatting numeric values in annotations with monospace font

- .storybook/global.css
- .storybook/preview.js
- src/feature/candlestick-chart/candlestick-chart.stories.tsx
- src/feature/candlestick-chart/candlestick-chart.tsx
- src/ui/components/plot-container/plot-container.tsx
- Expose pane change callback
- Make main pane greedily take space
- Make studies not scale due to resizing
- Adjust story css to make testing resizing the chart easier
> feat: pane configuration
